name = "lune_utils/dotenv_luau"
version = "0.1.0"
description = "DotEnv in luau"
authors = ["0xJWLabs <hi@0xjwlabs.dev>"]
repository = "https://github.com/lune-utils/dotenv-luau"
license = "MIT"

[engines]
lune = "^0.9.4"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
